# MagedIn - Magento DockerLab
# (https://github.com/magedin/magento-dockerlab)
version: "3.5"

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"
    networks:
      - magedin
