#!/usr/bin/env bash

source ./.env

HOST="$BASE_URL"
UPSTREAM="fastcgi_$(./var/actions/random)"

[ -z "$HOST" ] && echo "There's no BASE_URL specified. Please check the file .env." && exit

TEMPLATE=./var/template/nginx/magento2.conf
DEST=config/nginx/conf.d/"$HOST".conf

if [ -f $DEST ]; then
  rm -rf $DEST
fi

bin/mkcert-generate $HOST

cp $TEMPLATE $DEST
sed -i -e "s/{{host}}/$HOST/g" $DEST
sed -i -e "s/{{upstream}}/$UPSTREAM/g" $DEST
