#!/usr/bin/env bash

function isXdebugEnabled() {
    RESULT=$(bin/php | grep "Xdebug")

    if [ -z "$RESULT" ]; then
        return 0;
    else
        return 1;
    fi
}

function disableXdebug() {
  bin/cli sed -i -e 's/^zend_extension/\;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  bin/restart php
  echo "Xdebug has been disabled."
}

function enableXdebug() {
  bin/cli sed -i -e 's/^\;zend_extension/zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  bin/restart php
  echo "Xdebug has been enabled."
}
