#!/usr/bin/env bash

function isXdebugEnabled() {
    RESULT=$(bin/php -m | grep "Xdebug")

    if [ -z "$RESULT" ]; then
        return 1;
    else
        return 0;
    fi
}


function rstartContainers() {
  bin/restart php &> /dev/null;
}


function disableXdebug() {
    if ( ! isXdebugEnabled ); then
        echo "Xdebug is already disabled."
        exit 0;
    fi

    echo "Disabling Xdebug..."
    bin/cli sed -i -e 's/^zend_extension/\;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    rstartContainers
    echo "Xdebug has been disabled."
}


function enableXdebug() {
    if ( isXdebugEnabled ); then
        echo "Xdebug is already enabled."
        exit 0;
    fi

    echo "Enabling Xdebug..."
    bin/cli sed -i -e 's/^\;zend_extension/zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    rstartContainers
    echo "Xdebug has been enabled."
}


function toggleXdebug() {
    if ( isXdebugEnabled ); then
        disableXdebug
    else
        enableXdebug
    fi
}