#!/usr/bin/env bash
DOCKER_IP=$(var/actions/docker_ip)
COMPOSE_DEV=./docker-compose.dev.yml

sed -i -e 's/#extra_hosts:/extra_hosts:/g' $COMPOSE_DEV
sed -i -e "s/host.docker.internal:IP/host.docker.internal:$DOCKER_IP/g" $COMPOSE_DEV
sed -i -e 's/#  - "host/  - "host/g' $COMPOSE_DEV
