# MagedIn - Magento DockerLab
# (https://github.com/magedin/magento-dockerlab)
version: "3.5"

services:
  varnish:
    image: varnish:6
    depends_on:
      - nginx
    ports:
      - "8080:80"
      - "4443:443"
    networks:
      - magedin
    volumes:
      - ./config/varnish/:/etc/varnish
