# MagedIn - Magento DockerLab
# (https://github.com/magedin/magento-dockerlab)
version: "3.5"

services:
  php:
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
